# render.yaml para el despliegue en Render
services:
  - type: web # Servicio para tu backend Django
    name: mi-plataforma-backend # Nombre de tu servicio backend (cámbialo si quieres)
    env: python
    buildCommand: |
      # Instala dependencias de Python
      pip install -r requirements.txt
      # Navega a la carpeta del frontend y construye la aplicación React
      cd frontend
      npm install
      npm run build
      cd .. # Regresa a la raíz del proyecto
      # Recolecta los archivos estáticos de Django y la app React
      python manage.py collectstatic --noinput
      # Ejecuta las migraciones de la base de datos
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application # Comando para iniciar el servidor Django
    # Ruta al archivo wsgi.py de tu proyecto
    healthCheckPath: /admin/login/ # Una ruta para que Render sepa que tu app está viva
    plan: free # Puedes elegir starter o superior si necesitas más recursos
    autoDeploy: true # Despliega automáticamente cada vez que haya un push a la rama conectada
    envVars:
      - key: DATABASE_URL # Variable de entorno para la URL de la base de datos
        fromDatabase: mi-plataforma-cursos-db # Nombre de la base de datos que creaste en Render (¡DEBE COINCIDIR!)
      - key: SECRET_KEY # Variable de entorno para la clave secreta de Django
        generateValue: true # Render generará una clave segura automáticamente
      - key: WEB_CONCURRENCY # Recomendado para Gunicorn
        value: 4 # Puedes ajustarlo según tu plan
      - key: DEBUG_VALUE # Setear a False para producción
        value: "False"
      - key: ALLOWED_HOSTS
        value: "${RENDER_EXTERNAL_HOSTNAME}" # Render llenará esto con el dominio público de tu app
