# Generated by Django 5.2.5 on 2025-08-06 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('descripcion_corta', models.TextField()),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='cursos_portadas/')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_texto', models.TextField()),
                ('ejercicio_interactivo', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='cursos.curso')),
            ],
        ),
    ]
