# Generated by Django 5.2.5 on 2025-08-17 22:52

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='contenido_texto',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='ejercicio_interactivo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
